### ISSUE TITLE
Ninja parser issue

### ISSUE THREAD

**Issue by Hazelyn** [Icehunter/ffxivapp#56]
I was just testing the parser out and noticed that it seems to track everything except the DoT from multilate, and Doton. I understand tracking doton may be difficult or impossible, but the chat log clearly states when it applies multilate, is there a reason it isn't tracked?

**Comment by Icehunter** [comment]
I have it here:
https://github.com/Icehunter/ffxivapp-plugin-parse/blob/master/FFXIVAPP.Plugin.Parse/Helpers/DamageOverTimeHelper.cs#L349

I'm not at a high enough level though to use that skill yet.

I figured out why and it's because it's not in here anywhere:

https://github.com/Icehunter/ffxivapp-common/blob/master/FFXIVAPP.Common/Helpers/StatusEffectHelper.cs

Because of that it gets skipped over. I'm going to see after the launch if someone can tell me the ID of that. They aren't the same as DB id's.

**Comment by Icehunter** [comment]
Added mutilate to status effects.

https://github.com/Icehunter/ffxivapp-common/blob/master/FFXIVAPP.Common/Helpers/StatusEffectHelper.cs#L5936

Using DX9 client let me know if that shows up for you now. :)
